"""Initial schema with all models

Revision ID: 09ec7939c5c5
Revises: 
Create Date: 2025-11-03 23:52:47.349502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09ec7939c5c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_message_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('SMARTENGAGE', 'COACHNOVA', name='agent_type'), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False, comment='e.g., renewal_reminder, punctuality_coaching'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='System prompt for OpenAI'),
    sa.Column('example_user_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Example context JSON for testing'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_templates_agent_type'), 'ai_message_templates', ['agent_type'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SMARTENGAGE', 'COACHNOVA', name='campaign_type'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', name='campaign_status'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User segmentation filters'),
    sa.Column('feature_flag', sa.String(length=100), nullable=True, comment='Feature flag for canary rollouts'),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Campaign statistics: {users_targeted, users_reached, conversions, ...}'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_run_at'), 'campaigns', ['run_at'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_type'), 'campaigns', ['type'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SNAPSHOT_DAILY', 'CAMPAIGN_RUNNER', 'NOTIFIER', 'OTHER', name='job_type'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Job-specific configuration and parameters'),
    sa.Column('lock_key', sa.BigInteger(), nullable=True, comment='Used with pg_try_advisory_lock for distributed locking'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_scheduled_for'), 'jobs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('CLEANING', 'BEAUTY', 'ELECTRICAL', 'OTHER', name='service_category'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'WORKER', 'ADMIN', name='user_type'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR email IS NOT NULL', name='user_contact_required'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('typical_services', sa.ARRAY(sa.String()), nullable=False, comment='Frequently booked service categories'),
    sa.Column('last_booking_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_last_booking_at'), 'customers', ['last_booking_at'], unique=False)
    op.create_table('user_activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('APP_OPEN', 'BOOKING_CREATED', 'MESSAGE_CLICKED', 'NOTIFICATION_OPENED', 'DEEPLINK_FOLLOWED', 'BOOKING_COMPLETED', 'REVIEW_SUBMITTED', 'WORKER_SHIFT_START', 'WORKER_SHIFT_END', name='event_type'), nullable=False),
    sa.Column('source', sa.Enum('PUSH', 'SMS', 'APP', 'WEB', 'SYSTEM', name='event_source'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_events_correlation_id'), 'user_activity_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_user_activity_events_event_type'), 'user_activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_activity_events_occurred_at'), 'user_activity_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_user_activity_events_user_id'), 'user_activity_events', ['user_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('preferred_areas', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('work_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Work schedule: {mon: ['09:00-18:00'], ...}"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opt_in_voice', sa.Boolean(), nullable=False, comment='Whether worker has opted in for voice coaching'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'WORKER', name='message_role'), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='smartengage or coachnova'),
    sa.Column('channel', sa.Enum('SMS', 'APP_PUSH', 'WHATSAPP', 'IN_APP', name='message_channel'), nullable=False),
    sa.Column('message_type', sa.Enum('REMINDER', 'COACHING', 'BURNOUT_CHECK', 'UPSELL', name='message_type'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('user_response', sa.Enum('CLICKED', 'REPLIED', 'IGNORED', 'BOOKED', 'ACKNOWLEDGED', name='user_response'), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True, comment='OpenAI model used (e.g., gpt-4o-mini)'),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('safety_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Safety filter results'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['ai_message_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_agent_type'), 'ai_messages', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_messages_correlation_id'), 'ai_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_delivery_status'), 'ai_messages', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_worker_id'), 'ai_messages', ['worker_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('deep_link_token', sa.UUID(), nullable=True, comment='Short-lived token for deep link booking flow'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name='booking_finish_after_start'),
    sa.CheckConstraint('started_at IS NULL OR started_at >= scheduled_at', name='booking_start_after_schedule'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deep_link_token')
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_at'), 'bookings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_worker_id'), 'bookings', ['worker_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=False, comment="Derived attributes like 'late', 'rude', 'friendly'"),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='review_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_bookings_worker_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_ai_messages_worker_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_delivery_status'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_correlation_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_agent_type'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('workers')
    op.drop_index(op.f('ix_user_activity_events_user_id'), table_name='user_activity_events')
    op.drop_index(op.f('ix_user_activity_events_occurred_at'), table_name='user_activity_events')
    op.drop_index(op.f('ix_user_activity_events_event_type'), table_name='user_activity_events')
    op.drop_index(op.f('ix_user_activity_events_correlation_id'), table_name='user_activity_events')
    op.drop_table('user_activity_events')
    op.drop_index(op.f('ix_customers_last_booking_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_type'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scheduled_for'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_campaigns_type'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_run_at'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_ai_message_templates_agent_type'), table_name='ai_message_templates')
    op.drop_table('ai_message_templates')
    # ### end Alembic commands ###
